plugins {
    id 'com.android.application'
}

android {
    namespace 'com.joseph.miasistente'
    compileSdk 36

    defaultConfig {
        applicationId 'com.joseph.miasistente'
        minSdk 26
        targetSdk 36
        versionCode 9
        versionName '0.5.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
